#pragma once

template <class T>
class CProxy_ISloggerEvents : public IConnectionPointImpl<T, &__uuidof( _ISloggerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
